server:
  port: 9027

# spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

spring:
  datasource:
    url: jdbc:postgresql://ec2-174-129-227-51.compute-1.amazonaws.com:5432/d7mmhbbmj87s81
    username: xrsekjjydtyovl
    password: 71253291278b33a5e1c2315b066675ec7764d3d7e8f307c12acc528282d941cf
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update 